### ISSUE TITLE
A/C struggle to join the localizer

### ISSUE THREAD

**Issue by n8rzz** [n8rzz/atc#66] opened 2016-11-07 22:45 UTC
https://github.com/zlsa/atc/issues/711

**Comment by n8rzz** [comment] 2016-11-07 23:00
<img width="744" alt="screen shot 2016-11-07 at 5 00 22 pm" src="https://cloud.githubusercontent.com/assets/3325985/20079740/b98b3d3a-a50b-11e6-90ad-5b961a0f85d8.png">

**Comment by n8rzz** [comment] 2016-11-07 23:02
hmm, I thought we'd addressed this issue with #2.  At a very brief first glance this looks like it may be a difference issue, it's certainly drawing the course differently.

**Comment by n8rzz** [comment] 2016-11-09 00:39
@erikquinn I'm going to need your eyes on this one.  I'm still digging but so far I have not been able to find any major differences in the logic between v2 and v3.  The logic is very similar and nothing has jumped out at me yet.

**Comment by n8rzz** [comment] 2016-11-11 12:51
@erikquinn I'm completely stumped on this one.  Could you take a peak at this when you have some time?

This bug is reproducible on KSFO with an aircraft arriving on the BRS2 arrival and intercepting the localizer somewhere north or west of SWELS.  For aircraft arriving from the east to north east, they seem to be able to intercept just fine and have correctly drawn paths.

I'm sure I'm just missing something simple. I know I'm not getting `_clamp`ed again, cause those are all gone.  I'll bet is a math thing somewhere, though.

**Comment by erikquinn** [comment] 2016-11-11 18:48
I think it's the projection only that is messed up (which needs other fixes anyway). I'll have a look when I get home.

**Comment by n8rzz** [comment] 2016-11-11 19:02
Sounds good. I was looking at it again this morning and I think I did get clamped again. There are two spots in the AircraftInstanceModel where it looks like the arguments are in the wrong order.

**Comment by erikquinn** [comment] 2016-11-11 23:49
Reproduced. 

> Sounds good. I was looking at it again this morning and I think I did get clamped again. There are two spots in the AircraftInstanceModel where it looks like the arguments are in the wrong order.

That might make sense; one would be from the code section below. But reordering them properly doesn't really seem to fix it.

---

Truth time-- I've made countless failed attempts over the last 6 months to figure out this section has been a nightmare that has consumed about half the time I spend working on the project. I have been staring at the same problem for way too long, and don't think I will be able to come up with a good resolution. It doesn't seem like it should be that hard, but I can't come up with a way to make it work. I dumped another three hours at the problem, and still have nothing. Maybe I'm just a bufoon, I don't know, all I know is I'm sick of trying to figure this one out.

This is the section that's screwing it all up, from `AircraftInstanceModel.js:2088`:

``` javascript
                if (should_attempt_intercept || in_the_window) {  // time to begin turn
                    const severity_of_correction = 50;  // controls steepness of heading adjustments during localizer tracking
                    const tgtHdg = angle + (offset_angle * -severity_of_correction);
                    const minHdg = angle - degreesToRadians(30);
                    const maxHdg = angle + degreesToRadians(30);
                    this.target.heading = clamp(tgtHdg, minHdg, maxHdg);
                }
```

It needs to be able to target headings such that the aircraft makes a SINGLE, SMOOTH turn from any angle onto the localizer. Currently it works alright, but doesn't work well in very high angle intercepts, and often overcompensates from localizer overshoots. The problem is more severe the shorter the distance from the runway during turn-on.

**Comment by n8rzz** [comment] 2016-11-11 23:58
we must be missing something because under the same circumstances in the current version, we don't have this problem.  It's got to be something simple, these types of things usually are.  I'm going to try and figure out what differs between the versions.

**Comment by n8rzz** [comment] 2016-11-12 01:44
there is some definite math differences, the first spot is in the result of `angle_offset`.  Seems like a good time to start adding tests to some of these math functions.

**Comment by n8rzz** [comment] 2016-11-12 02:52
that seems to steam from the `radians_normalize` method that was added to `Runway.angle` which is getting run again when that property gets reassigned to `angle` (AircraftInstanceModel ln: 1983).  reverting that change still doesn't solve the problem, though.

**Comment by erikquinn** [comment] 2017-01-19 16:12
Covered by openscope/openscope#38. Closing.

**Closed as completed by erikquinn** 2017-01-19 16:12 UTC
Labels: bug, help wanted, closed during openscope migration
